name: CI

on: [push, pull_request]

jobs:
    lint:
        name: 'Lint'
        runs-on: ubuntu-latest
        permissions:
            checks: write
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 21
                  cache: 'npm'
            - name: Install Node Dependencies
              run: npm ci

            # Linting
            - name: Create ESLint Report
              run: node_modules/.bin/eslint --output-file eslint_report.json --format json .
              continue-on-error: true
            - name: Annotate Code Linting Results
              uses: ataylorme/eslint-annotate-action@v3
              continue-on-error: true
              with:
                  report-json: 'eslint_report.json'
            - name: Run ESLint
              run: node_modules/.bin/eslint .

    build:
        name: 'Build'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 21
                  cache: 'npm'
            - name: Install Node Dependencies
              run: npm ci
            # Build
            - name: Build
              run: npm run build
