name: CI

on: [push, pull_request]

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'
      - name: Install Node Dependencies
        run: npm ci

      # Linting
      - name: Run ESLint
        run: node_modules/.bin/eslint --output-file eslint_report.json --format json .
        continue-on-error: true
      - name: Create ESLint Summary
        run: node_modules/.bin/eslint --no-color . >> $GITHUB_STEP_SUMMARY
        continue-on-error: false
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        continue-on-error: true
        with:
          report-json: "eslint_report.json"
      - name: Upload ESLint report
        uses: actions/upload-artifact@v4
        with:
          name: eslint_report.json
          path: eslint_report.json

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'
      - name: Install Node Dependencies
        run: npm ci
      # Build
      - name: Rename config files
        run: |
          for i in config/*.example.*
          do
            mv "$i" "`echo $i | sed 's/.example//'`"
          done
      - name: Build
        run: npm run build